Hw03 mongodb
Vitalina-Oleksiienko/nodejs-hw-rest-api pull request #2
Opened 2022-01-19 14:48 UTC by Vitalina-Oleksiienko

2022-01-22 21:38 UTC, KirillKulakow commented on .env
> +URI_DB=mongodb+srv://admin:1991@cluster0.gn7xc.mongodb.net/db-contacts
удалить файл из гита и добавить в гитигнор

2022-01-22 21:42 UTC, KirillKulakow commented on libs/db.js
> +import pkg from 'mongoose'
называй переменные понятными наименованиями

2022-01-22 21:43 UTC, KirillKulakow commented on routes/api/contacts/index.js
> +router.patch('/:contactId', async (req, res, next) => {
что это?

2022-01-22 21:44 UTC, KirillKulakow requested changes
Need fix

2022-01-22 22:15 UTC, Vitalina-Oleksiienko commented on libs/db.js
> +import pkg from 'mongoose'
скоротила package, окей поправила

2022-01-22 22:15 UTC, Vitalina-Oleksiienko commented
поправила все коменты

2022-01-26 18:15 UTC, KirillKulakow commented on .env
> +URI_DB=mongodb+srv://admin:1991@cluster0.gn7xc.mongodb.net/db-contacts
файл не удален из гитхаба

2022-01-26 18:16 UTC, KirillKulakow requested changes
need fix

2022-01-26 18:53 UTC, Vitalina-Oleksiienko commented on .env
> +URI_DB=mongodb+srv://admin:1991@cluster0.gn7xc.mongodb.net/db-contacts
видалила

2022-01-26 19:02 UTC, KirillKulakow approved these changes

2022-01-26 19:38 UTC, merged